# Generated by Django 5.2 on 2025-04-05 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='encrypted_private_key',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='private_key_salt',
            field=models.CharField(max_length=256),
        ),
    ]
