# Generated by Django 5.1.7 on 2025-03-28 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_customuser_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='verification_docs',
            field=models.ImageField(blank=True, null=True, upload_to='verification_docs/'),
        ),
    ]
