name: RansomHub Backend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    env:
      DJANGO_SETTINGS_MODULE: backend.settings
      PYTHON_VERSION: '3.10'
      PIP_CACHE_DIR: ./.pip_cache

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          path: RansomHub-Backend

      - name: Sync Files to /var/www
        run: |
          sudo rsync -av --delete $GITHUB_WORKSPACE/RansomHub-Backend/ /var/www/RansomHub-Backend/
          sudo chown -R iiitd:iiitd /var/www/RansomHub-Backend/

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Remove old virtual environment (if exists)
        run: |
          if [ -d "/var/www/RansomHub-Backend/venv" ]; then
            rm -rf /var/www/RansomHub-Backend/venv
          fi

      - name: Create a new virtual environment
        run: |
          cd /var/www/RansomHub-Backend
          python3 -m venv venv

      - name: Install dependencies
        run: |
          cd /var/www/RansomHub-Backend
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Apply database migrations
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/mydatabase
        run: |
          cd /var/www/RansomHub-Backend
          source venv/bin/activate
          python manage.py migrate

      - name: Collect static files
        run: |
          cd /var/www/RansomHub-Backend
          source venv/bin/activate
          python manage.py collectstatic --noinput

      - name: Restart Gunicorn service
        run: |
          sudo systemctl restart gunicorn
