name: RansomHub Backend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    env:
      DJANGO_SETTINGS_MODULE: myproject.settings.production
      PYTHON_VERSION: '3.10'
      PIP_CACHE_DIR: ./.pip_cache

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          path: RansomHub-Backend

      - name: Sync Files to /var/www
        run: |
          sudo rsync -av --delete $GITHUB_WORKSPACE/RansomHub-Backend/ /var/www/RansomHub-Backend/
          sudo chown -R iiitd:iiitd /var/www/RansomHub-Backend/

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          cd /var/www/RansomHub-Backend
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Apply database migrations
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/mydatabase
        run: |
          cd /var/www/RansomHub-Backend
          source venv/bin/activate
          python manage.py migrate

      - name: Collect static files
        run: |
          cd /var/www/RansomHub-Backend
          source venv/bin/activate
          python manage.py collectstatic --noinput

      - name: Stop Existing PM2 Process (if any)
        run: pm2 delete ransomhub-backend || echo "No existing backend process found."

      - name: Start Gunicorn Server with PM2
        run: |
          cd /var/www/RansomHub-Backend
          source venv/bin/activate
          RUNNER_TRACKING_ID="" && pm2 start gunicorn --name "ransomhub-backend" -- gunicorn myproject.wsgi:application --bind unix:/var/www/RansomHub-Backend/gunicorn.sock --workers 3

      - name: Save PM2 Process List
        run: pm2 save
